name: AITrendFinder

on:
  schedule:
    - cron: '0 22 * * *'  # 한국시간으로 매일 오전 7시에 실행
  workflow_dispatch:  # 수동 실행 허용

jobs:
  find-trends:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # 최대 15분 후 작업 강제 종료
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: 종속성 설치
        run: npm ci

      - name: Trend Finder 실행
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          X_API_BEARER_TOKEN: ${{ secrets.X_API_BEARER_TOKEN }}
          NOTIFICATION_DRIVER: "notion"
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          node -r ts-node/register src/index.ts
          # 프로세스 종료를 위해 exit 추가
          echo "작업 완료, 프로세스 종료 중..."
          sleep 5  # 5초 대기 후 종료 (남은 백그라운드 작업 완료 시간 확보)
          exit 0
